M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Tue 08 Nov 2022 12:59:15 AM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-08T00:59:15-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.750
%
G90
G05
T1
X141.0Y-60.0
X141.0Y-111.0
T2
X141.0Y-85.45
X141.0Y-94.0
X143.0Y-85.45
X143.0Y-94.0
X145.0Y-85.45
X145.0Y-94.0
T0
M30
