M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Mon 07 Nov 2022 11:46:56 PM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-07T23:46:56-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X117.0Y-69.0
X138.0Y-124.0
X144.0Y-91.0
X174.0Y-109.0
X179.0Y-72.0
T0
M30
